### ISSUE TITLE
有点问题用不了耶...

### ISSUE THREAD

**Issue by onetuzi** [1343890272/weibo_comments#5]
```
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\weibo_points-master\main.py", line 1627, in <module>
    cid = find_super_topic(st_name)
  File "C:\Users\Administrator\Desktop\weibo_points-master\main.py", line 1020, in find_super_topic
    return re.findall('100808[\d\w]{32}', r.text)[0]
IndexError: list index out of range
```

报错了，空列表嘛

**Comment by wxy1343** [comment]
传的什么参数，打印一下r.text看看
